import '~/styles/globals.css';
import { ClerkProvider, SignedOut, RedirectToSignIn } from '@clerk/nextjs';

import { GeistSans } from 'geist/font/sans';

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`font-sans ${GeistSans.variable}`}>
        <ClerkProvider>
          {children}
          <SignedOut>
            <RedirectToSignIn />
          </SignedOut>
        </ClerkProvider>
      </body>
    </html>
  );
}
