import '~/styles/globals.css';
import { ClerkProvider } from '@clerk/nextjs';

import { GeistSans } from 'geist/font/sans';
import { Navbar } from '~/components/common';
import MobileNavbar from '~/components/common/navbar/mobile';

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`font-sans ${GeistSans.variable}`}>
        <ClerkProvider>
          <div className='py-[7dvh]'>
            <Navbar />
            {children}
            <MobileNavbar />
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
