import '~/styles/globals.css';
import { ClerkProvider, ClerkLoaded, ClerkLoading } from '@clerk/nextjs';

import { GeistSans } from 'geist/font/sans';
import { Navbar, PageProgress } from '~/components/common';

import MobileNavbar from '~/components/common/navbar/mobile';
import { LoadingScreen } from '~/screens';

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`font-sans ${GeistSans.variable}`}>
        <ClerkProvider>
          <ClerkLoading>
            <LoadingScreen />
          </ClerkLoading>
          <ClerkLoaded>
            <div className='flex h-screen flex-col'>
              <PageProgress />
              <Navbar />
              <div className='hide-scrollbar h-full overflow-scroll'>
                {children}
              </div>
              <MobileNavbar />
            </div>
          </ClerkLoaded>
        </ClerkProvider>
      </body>
    </html>
  );
}
